theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "neon"

local: en-GB

title: "Cyber-F0x Blog"

name: Cyber-F0x


description: Fox loving hackerman with taste for exploit develpoment

avatar: https://avatars0.githubusercontent.com/u/34145491?s=400&u=a8e6f9f1afe55ecf0a8c4dc634e84d36b32bc8c1&v=4
teaser: https://avatars0.githubusercontent.com/u/34145491?s=400&u=a8e6f9f1afe55ecf0a8c4dc634e84d36b32bc8c1&v=4

breadcrumbs: true
